version: 2
jobs:
  build:
    working_directory: ~/graphql-xtext
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout
      - restore_cache:
          # ignoring target, tests, ui project POMs (very few changes, if any)
          key: v1-deps-{{ checksum "pom.xml" }}-{{checksum "com.intuit.graphql.parent/pom.xml" }}-{{checksum "com.intuit.graphql.parent/com.intuit.graphql/pom.xml" }}-{{ checksum "com.intuit.graphql.parent/com.intuit.graphql.ide/pom.xml" }}

      - run:
          name: Maven Build
          command: mvn install
      - save_cache:
          paths:
            - ~/.m2
          key: v1-deps-{{ checksum "pom.xml" }}-{{checksum "com.intuit.graphql.parent/pom.xml" }}-{{checksum "com.intuit.graphql.parent/com.intuit.graphql/pom.xml" }}-{{ checksum "com.intuit.graphql.parent/com.intuit.graphql.ide/pom.xml" }}

      - store_test_results:
          path: com.intuit.graphql.parent/com.intuit.graphql.tests/target/surefire-reports

  release:
    steps:
      - attach_workspace:
          at: ~/auto
      - run:
          name: Release
          command: npx auto shipit

workflows:
  version: 2
  ci_builds:
    jobs:
      - build
  release:
    requires:
      - install
